apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "resource.name" . }}
  namespace: {{ include "resource.namespace" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "resource.appName" . }}
        helm.sh/chart: {{ include "chart.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecrets.default.name }}
      containers:
      {{ range $i, $strategy := .Values.strategies -}}     
      - name: {{ $strategy.name }}
        image: {{ include "image.hummingbot.repository" $ }}
        imagePullPolicy: {{ default "Always" $.Values.global.image.hummingbot.imagepullPolicy }}
        args: ["sh", "-c", "./init.sh" ]
        env: 
        - name: "CONFIG_PASSWORD"
          value: {{ $.Values.global.options.config_password }}
        - name: "STRAT_CONF_FILE"
          value: {{ $strategy.config }}
        volumeMounts:
        - mountPath: /conf-master-data
          name: config-data
        - mountPath: /home/hummingbot/conf
          name: conf-{{ $strategy.subfolder }}-vol
        - mountPath: /home/hummingbot/logs
          name: log-{{ $strategy.subfolder }}-vol 
        - lifecycle: 
          preStop:
            exec: 
              command: ["sh", "-t", "tmux send-keys -t hummingbot:hbstrat stop Enter; sleep 5; tmux send-keys -t hummingbot:hbstrat stop Enter"; sleep 5;]
      {{ end -}}
      volumes:
      {{ range $i, $strategy := .Values.strategies -}}   
      - name: log-{{ $strategy.subfolder }}-vol
        persistentVolumeClaim:
          claimName: {{include "hummingbot.logs.pv.name" $ }}-{{ $strategy.subfolder }}      
      - name: conf-{{ $strategy.subfolder }}-vol
        persistentVolumeClaim:
          claimName: {{include "hummingbot.conf.pv.name" $ }}-{{ $strategy.subfolder }} 
      {{ end -}}                      
      - name: config-data
        configMap:
          name: hummingbot-conf
          items:
          - key: conf_global.yml
            path: conf_global.yml 
